[versions]
accompanistFlowlayout = "0.20.0"
agp = "8.11.1"
annotation = "1.9.1"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
datastorePreferences = "1.1.6"
firebaseAuth = "23.2.0"
firebaseBom = "33.13.0"
firebaseFirestoreKtx = "25.1.4"
firebaseStorage = "21.0.1"
glanceAppwidget = "1.1.1"
glanceMaterial3 = "1.1.1"
googleid = "1.1.1"
kotlin = "2.1.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.12.00"
appcompat = "1.7.0"
lottieCompose = "6.5.2"
material = "1.12.0"
composeNavigation = "2.9.0"
composeMaterial = "1.8.1"
material3Android = "1.4.0"
playServicesAuth = "21.0.0"
playServicesLocation = "21.3.0"
serialization = "1.7.3"
uiTestJunit4Android = "1.8.1"
accompanistPagerIndicators = "0.28.0"
accompanistPager = "0.28.0"
coilCompose = "3.0.4"
converterGson = "2.9.0"
coreSplashscreen = "1.0.1"
gson = "2.10.1"
hiltAndroidCompiler = "2.51.1"
hiltCompiler = "1.2.0"
loggingInterceptor = "4.9.3"
pagingCompose = "3.3.6"
retrofit = "2.9.0"
roomKtx = "2.7.1"
animation = "1.8.1"
workRuntimeKtx = "2.10.1"
material3 = "1.4.0"
jetbrainsKotlinJvm = "2.1.10"
room = "2.7.2"
androidTools = "31.12.0"
material3Adaptive = "1.1.0"
coroutines = "1.10.2"
ksp = "2.1.0-1.0.29"
pager = "1.10.1"

projectAppId = "com.example.allinone"
projectVersionName = "1.0.0"
projectVersionCode = "1"
projectMinSdkVersion = "26"
projectTargetSdkVersion = "36"
projectCompileSdkVersion = "36"
material3Version = "1.0.0-alpha13"
uiGraphics = "1.10.0"
playServicesAuthVersion = "21.5.0"

[libraries]

# flow layout
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanistFlowlayout" }

# animation
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }

# data store
androidx-compose-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material3Android" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

# glance
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glanceAppwidget" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glanceMaterial3" }

androidx-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3Adaptive" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
# work manager
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

# firebase
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseStorage" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# LottieFiles
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4Android" }

# splash-screen
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

# navigation
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}

# mvvm
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }

# paging3
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
accompanist-pager = { module = "com.google.accompanist:pager", version.ref = "accompanistPager" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingCompose" }
accompanist-pager-indicators = { module = "com.google.accompanist:pager-indicators", version.ref = "accompanistPagerIndicators" }

# room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-svg-compose = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilCompose" }

coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }

# gson
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# dagger hilt 2
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidCompiler" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltCompiler" }

# retrofit
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

# location
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

# coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# pager
foundation-pager = { group = "androidx.compose.foundation", name = "foundation", version.ref = "pager" }

# gradle
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
android-tools-common = { module = "com.android.tools:common", version.ref = "androidTools" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
material3 = { group = "androidx.xr.compose.material3", name = "material3", version.ref = "material3Version" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuthVersion" }

[bundles]
firebase = [
    "firebase-auth",
    "firebase-firestore-ktx",
    "firebase-storage",
    "googleid",
    "credentials-play-services-auth",
    "firebase-bom",
]
compose = [
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-material3",
    "androidx-material3-adaptive",
    "androidx-compose-animation",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling-preview",
]
compose-debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest",
]
room = [
    "room-runtime",
    "room-ktx",
]
hilt = [
    "hilt-android",
    "hilt-navigation-compose"
]
hilt-compiler = [
    "androidx-hilt-compiler",
    "hilt-compiler",
    "hilt-android-compiler",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
room = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }


allinone-android-application = { id = "allinone.android.application", version = "unspesified" }
allinone-jvm-library = { id = "allinone.jvm.library", version = "unspesified" }
allinone-android-library = { id = "allinone.android.library", version = "unspesified" }
allinone-android-library-compose = { id = "allinone.android.library.compose", version = "unspesified" }